// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Modulo1 from "./islands/Modulo1.tsx";
import * as $Modulo2 from "./islands/Modulo2.tsx";
import * as $Modulo3 from "./islands/Modulo3.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Modulo1.tsx": $Modulo1,
    "./islands/Modulo2.tsx": $Modulo2,
    "./islands/Modulo3.tsx": $Modulo3,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
